# This file was generated by GoReleaser. DO NOT EDIT.
cask "saral" do
  version "0.4.1"

  on_macos do
    on_arm do
      sha256 "9cc1b5b262d4b9554159a59e09529b3a044a823fd6b5f4f55c17459981d62428"
      url "https://github.com/varijkapil13/saral/releases/download/v#{version}/saral_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "3474600f8d0b40b92c6afd72278bc9a7b4ac24b4d336d5f6aecf00df1e6adc51"
      url "https://github.com/varijkapil13/saral/releases/download/v#{version}/saral_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "6424d89d7a7e157f8ff84f07b32aa2fbdd7c680a61a7e4086d742cddc9c358ce"
      url "https://github.com/varijkapil13/saral/releases/download/v#{version}/saral_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e69d7c18b4a2f0cc026fffc4b482465a0d5663f1a0866900a36956bf3a615acc"
      url "https://github.com/varijkapil13/saral/releases/download/v#{version}/saral_#{version}_linux_amd64.tar.gz"
    end
  end

  name "saral"
  desc "Jira in your terminal, made simple"
  homepage "https://github.com/varijkapil13/saral"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "saral"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"], print_stderr: false).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/saral"]
    end
  end

  zap trash: [
      "~/.config/saral",
      "~/.cache/saral",
    ]

end
