# This file was generated by GoReleaser. DO NOT EDIT.
cask "saral" do
  version "0.4.5"

  on_macos do
    on_arm do
      sha256 "acd95e40c5e7b68497c107a38331c4c64e98ed45bcea8cddb26f9f11039bd001"
      url "https://github.com/varijkapil13/saral/releases/download/v#{version}/saral_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "092b897f9cb97f83b3ea56ac50ae0a51db0d44445ff8ae0522f89a99549a22c6"
      url "https://github.com/varijkapil13/saral/releases/download/v#{version}/saral_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "897414e845379173bd67adabe87b57cd5aed8fd6eaf37005622bfb7659fddb05"
      url "https://github.com/varijkapil13/saral/releases/download/v#{version}/saral_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "0a29d601edebc079c909a17bf247245a5a62701c7b6862cc725831abe17cc981"
      url "https://github.com/varijkapil13/saral/releases/download/v#{version}/saral_#{version}_linux_amd64.tar.gz"
    end
  end

  name "saral"
  desc "Jira in your terminal, made simple"
  homepage "https://github.com/varijkapil13/saral"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "saral"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"], print_stderr: false).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/saral"]
    end
  end

  zap trash: [
      "~/.config/saral",
      "~/.cache/saral",
    ]

end
