# This file was generated by GoReleaser. DO NOT EDIT.
cask "saral" do
  version "0.5.0"

  on_macos do
    on_arm do
      sha256 "a085a5266f2cba6e852f43a9b271a6be64bf34a812f7c4ad5d0127194382c47f"
      url "https://github.com/varijkapil13/saral/releases/download/v#{version}/saral_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "36c11b3c7af9079be97520569db53ba542fca84e09c498bb64929e8e7353d203"
      url "https://github.com/varijkapil13/saral/releases/download/v#{version}/saral_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "68bc4a329b244293048165e0af86e685d46546e1d69ef60baf16c8fecaae6198"
      url "https://github.com/varijkapil13/saral/releases/download/v#{version}/saral_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "32d7691e534b5e753a5ab7364630129a06a9d732b6cc82ebf1faae9afd4a3e5e"
      url "https://github.com/varijkapil13/saral/releases/download/v#{version}/saral_#{version}_linux_amd64.tar.gz"
    end
  end

  name "saral"
  desc "Jira in your terminal, made simple"
  homepage "https://github.com/varijkapil13/saral"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "saral"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"], print_stderr: false).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/saral"]
    end
  end

  zap trash: [
      "~/.config/saral",
      "~/.cache/saral",
    ]

end
